// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAP_2ZdHqclrTZBW4UOHM9hf9cafQmWAM',
    appId: '1:180996199152:android:667bbd76e6d678a7462835',
    messagingSenderId: '180996199152',
    projectId: 'tugas-app-cb480',
    storageBucket: 'tugas-app-cb480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAfZgtw7GPGtYpsUlgkvhYHWHzT7J8Kl0',
    appId: '1:180996199152:ios:e733f498a61f9cfa462835',
    messagingSenderId: '180996199152',
    projectId: 'tugas-app-cb480',
    storageBucket: 'tugas-app-cb480.appspot.com',
    androidClientId: '180996199152-7prhpg02silmmaesuv4j0i8tlr0380dr.apps.googleusercontent.com',
    iosClientId: '180996199152-06o35svhu2t0t4lqca1ic2b1ndt315ol.apps.googleusercontent.com',
    iosBundleId: 'com.mobile.aplikasiTugas',
  );
}
